
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 24 18:40:02 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int TIPOREAL = 3;
  public static final int LLCIE = 50;
  public static final int POR = 42;
  public static final int ENTERO = 34;
  public static final int CAP = 47;
  public static final int CCIE = 48;
  public static final int PUNTOCOMA = 37;
  public static final int ARRAY = 24;
  public static final int DELETE = 28;
  public static final int WRITE = 30;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int IGUAL = 58;
  public static final int RECORD = 23;
  public static final int LLAP = 49;
  public static final int TYPE = 12;
  public static final int OR = 7;
  public static final int CALL = 22;
  public static final int DIV = 43;
  public static final int MAYIGUAL = 57;
  public static final int IF = 15;
  public static final int ID = 33;
  public static final int ENDWHILE = 21;
  public static final int OF = 25;
  public static final int DIST = 59;
  public static final int EOF = 0;
  public static final int AMP = 53;
  public static final int ASIG = 38;
  public static final int TRUE = 9;
  public static final int PCIE = 46;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int CADENA = 32;
  public static final int MENOS = 41;
  public static final int MENOR = 54;
  public static final int NULL = 14;
  public static final int MOD = 44;
  public static final int TIPOINT = 2;
  public static final int MAYOR = 55;
  public static final int REAL = 35;
  public static final int PAP = 45;
  public static final int FLECHA = 52;
  public static final int ENDIF = 18;
  public static final int ELSE = 17;
  public static final int PUNTO = 51;
  public static final int NL = 31;
  public static final int READ = 29;
  public static final int WHILE = 19;
  public static final int MENIGUAL = 56;
  public static final int TIPOBOOL = 4;
  public static final int THEN = 16;
  public static final int TIPOSTRING = 5;
  public static final int PROC = 13;
  public static final int POINTER = 26;
  public static final int FALSE = 10;
  public static final int SEPSEC = 39;
  public static final int VAR = 11;
  public static final int DO = 20;
  public static final int MAS = 40;
}

