package alex;

public enum ClaseLexica {
		TIPOINT, TIPOREAL, TIPOBOOL, TIPOSTRING, AND, OR, NOT, TRUE, FALSE, 
		VAR, TYPE, PROC, NULL, IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, CALL, RECORD, 
		ARRAY, OF, POINTER, NEW, DELETE, READ, WRITE, NL, CADENA, 
		IDENTIF, ENTERO, REAL, COMA, PUNTOCOMA, ASIG, SEPSEC, MAS, MENOS, POR, DIV, MOD, PAP, PCIE, CAP, CCIE, LLAP, LLCIE, 
		PUNTO, FLECHA, AMP, MENOR, MAYOR, MENIGUAL, MAYIGUAL, IGUAL, DIST, EOF
}
