package alex;

public enum ClaseLexica {
		TIPOINT, TIPOREAL, TIPOBOOL, AND, OR, NOT, TRUE, FALSE, VARIABLE, ENTERO, REAL, PUNTOCOMA, 
		ASIG, SEPSEC, MAS, MENOS, POR, DIV, PAP, PCIE, MENOR, MAYOR, MENIGUAL, MAYIGUAL, IGUAL, DIST, EOF
}
