/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTiny1JavaCCConstants.java */
package c_ast_descendente;

public interface AnalizadorSintacticoTiny1JavaCCConstants {

  int EOF = 0;
  int letra = 1;
  int digPos = 2;
  int dig = 3;
  int pDec = 4;
  int pExp = 5;
  int TipoInt = 8;
  int TipoReal = 9;
  int TipoBool = 10;
  int TipoString = 11;
  int And = 12;
  int Or = 13;
  int Not = 14;
  int True = 15;
  int False = 16;
  int Var = 17;
  int Type = 18;
  int Proc = 19;
  int Null = 20;
  int If = 21;
  int Then = 22;
  int Else = 23;
  int Endif = 24;
  int While = 25;
  int Do = 26;
  int Endwhile = 27;
  int Call = 28;
  int Record = 29;
  int Array = 30;
  int Of = 31;
  int Pointer = 32;
  int New = 33;
  int Delete = 34;
  int Read = 35;
  int Write = 36;
  int Nl = 37;
  int Cadena = 38;
  int Id = 39;
  int Entero = 40;
  int Real = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digPos>",
    "<dig>",
    "<pDec>",
    "<pExp>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "\"var\"",
    "\"type\"",
    "\"proc\"",
    "\"null\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "<Cadena>",
    "<Id>",
    "<Entero>",
    "<Real>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\"->\"",
    "\"*\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
  };

}
